### ISSUE TITLE
FS0001 : The type 'BookService' is not compatible with the type 'IRemoteHandler'

### ISSUE THREAD

**Issue by BentTranberg** [fsbolero/Bolero#223] opened 2021-06-12 15:33 UTC
When I install the latest Bolero template, and create a new default Bolero project, it compiles and runs just fine, without actual warnings or errors. However, Visual Studio IntelliSense will complain. This is what it looks like.

![image](https://user-images.githubusercontent.com/15068882/121780979-00e44600-cba3-11eb-8e63-fa37f9d017ff.png)

And of course the Error List will show this error too, if the filter is set to IntelliSense or Build+IntelliSense.

FS0001 : The type 'BookService' is not compatible with the type 'IRemoteHandler'

I assume this is entirely a Visual Studio or FSharp problem. Though I am not absolutely sure, and in any case I wonder if there's something that can be done to make the error go away. It happens in my business projects too, after I updated from Bolero 0.16 to 0.17

Maybe it's just one more of countless annoyances that come and go in the latest Visual Studio versions.

Visual Studio 16.10.1

**Comment by Tarmil** [comment] 2021-06-16 13:25
Yes, I can reproduce this. It looks like an issue with inter-project references. In my case, when the project is clean I see this error, then after I build the solution, it disappears.

**Comment by Tarmil** [comment] 2021-06-16 13:39
That was with 16.10.0; now with 16.10.2 it stays red, like you 😬

**Comment by BentTranberg** [comment] 2021-06-16 14:20
I have reported similar problems in dotnet/fsharp long time ago. I dare not guess if there's a connection.

https://github.com/dotnet/fsharp/issues/3510
https://github.com/dotnet/fsharp/issues/8760

In any case, to me now the chances looks very slim that Bolero is involved, so I'm thinking just close and report in dotnet/fsharp next, and see what they say. But you are much more of an expert than I am, so I'll take your advice.

**Comment by Tarmil** [comment] 2021-06-27 16:36
After more tests, I figured out that this issue only happens when the HTML template type provider is used. For example a project created with `dotnet new bolero-app --html=false` works correctly. So the issue is probably with the handling of type providers in VS.

**Comment by BentTranberg** [comment] 2021-06-27 18:39
Ah, not at all surprised! Some of the problems I've reported to dotnet/fsharp has been related to type providers, and it's been about behavior much like with this one.

I don't think there's much point in reporting this to dotnet/fsharp, because I think they have plenty of reports and even repros that they can work with already. Several of my reports from years past that I think is related, was initially given highest priority, but gradually got lower priority, and a few still aren't fixed. I know two reasons why that is so. First, I don't think these issues truly bother anybody much. Second, these are the kind of problems that one expects will go away as a result of major improvements in certain areas. It's easier to just wait for that to happen.

**Comment by laenas** [comment] 2021-07-03 11:36
> After more tests, I figured out that this issue only happens when the HTML template type provider is used. For example a project created with `dotnet new bolero-app --html=false` works correctly. So the issue is probably with the handling of type providers in VS.

I suspect there's a more complicated cause here - because I've got an older-er Bolero project that I've upgraded to current and it's getting this error, despite not using or referencing the HTML Templating Provider.  I'm going to build the app back up, file-by-file, to try and figure out when precisely the behavior gets triggered.

**Comment by laenas** [comment] 2021-11-03 09:32
@BentTranberg @Tarmil 
Coming back to stuff of late and I am no longer seeing the problem.  I'm thinking upstream tooling has resolved this, can either of you confirm?

**Comment by BentTranberg** [comment] 2021-11-03 09:57
Yes, it appears to finally have been fixed. I've had it constantly I believe until quite recently.

I'm on VS 2022 Preview 7, platform net 5.0, Bolero 0.17.

**Comment by laenas** [comment] 2021-11-03 10:01
I'm not seeing it anymore on VS 2022 Preview 7, .NET 6, Bolero 0.17 - so I suspect the upstream FSC related stuff is resolved.  Hooray.  I never did figure out what was going on.

**Comment by Tarmil** [comment] 2021-11-03 13:38
I'll close this issue then, feel free to ask for reopening if it happens again.

**Closed by Tarmil** 2021-11-03 13:38 UTC
Labels: bug
