### ISSUE TITLE
Bolero.Remoting.IRemoteService is not assignable from

### ISSUE THREAD

**Issue by ADIX7** [fsbolero/Bolero#31] opened 2019-03-20 08:46 UTC
I try to use Remoting but I get "Error: System.InvalidOperationException: constrained call: Bolero.Remoting.IRemoteService is not assignable from BitTorrentFileServer.Service.WebService"

This is my type:
```
namespace BitTorrentFileServer.Service

open BitTorrentFileServer.Data
open Bolero.Remoting

type WebService =
    {
        getFolders : unit -> Async<Folder>
    }
    
    interface IRemoteService with
        member this.BasePath = "/api"
```

I created a test C# program. In it I could cast it to IRemoteService like this:
```
var a = new BitTorrentFileServer.Service.WebService(null);

IRemoteService b = (IRemoteService)a;

Console.WriteLine(b.BasePath);
```

**Comment by scitesy** [comment] 2019-03-20 12:20
I can confirm. I get a similar error in the browser console:
Error: System.ArgumentException: Cannot instantiate implementation type 'Bolero.Remoting.IRemoteHandler' for service type 'Bolero.Remoting.IRemoteHandler'. at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate (System.Collections.Generic.IEnumerable`1[T] descriptors) <0x20b9ee0 + 0x0016c> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor (System.Collections.Generic.IEnumerable`1[T] descriptors) <0x20ac9f0 + 0x00048> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor (System.Collections.Generic.IEnumerable`1[T] serviceDescriptors, Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback callback) <0x20ac290 + 0x00064> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor (System.Collections.Generic.IEnumerable`1[T] serviceDescriptors, Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback callback) <0x20ab910 + 0x00018> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine..ctor (System.Collections.Generic.IEnumerable`1[T] serviceDescriptors, Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback callback) <0x20ab608 + 0x00018> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor (System.Collections.Generic.IEnumerable`1[T] serviceDescriptors, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions options) <0x209a770 + 0x00076> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider (Microsoft.Extensions.DependencyInjection.IServiceCollection services, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions options) <0x209a050 + 0x0003c> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider (Microsoft.Extensions.DependencyInjection.IServiceCollection services) <0x2099c00 + 0x0000e> in <ef466db513bd4c67869506814ed622c5>:0 at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.CreateServiceProvider () <0x206ccd0 + 0x000f2> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.Build () <0x206c0b8 + 0x00034> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 at Client.Program.Main (System.String[] args) <0x201b588 + 0x0001e> in <ff901858503d456d983aab9353c4b999>:0

**Comment by ADIX7** [comment] 2019-03-20 12:26
Here is the full exception (mine is a little different):

```
Error: System.InvalidOperationException: constrained call: Bolero.Remoting.IRemoteService is not assignable from BitTorrentFileServer.Service.WebService
  at Bolero.Remoting.RemotingExtensions.Remote[T] (Bolero.IProgramComponent this) <0x2240ec0 + 0x00018> in <5c64400dc4d410eaa74503830d40645c>:0 
  at BitTorrentFileServer.Client.Main+FileServerApp.get_Program () <0x2240cc8 + 0x0000a> in <87b360f670124ec0866e539fa2fedc12>:0 
  at Bolero.ProgramComponent`2[model,msg].OnInit () <0x2240630 + 0x00016> in <5c64400dc4d410eaa74503830d40645c>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x222dd38 + 0x00038> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.SetDirectParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x223cb68 + 0x00084> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderRootComponent (System.Int32 componentId) <0x223bf98 + 0x00024> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x21acce8 + 0x00084> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRenderer () <0x2190f88 + 0x00078> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsync (System.Threading.CancellationToken cancellationToken) <0x2161560 + 0x000f8> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostExtensions.Run (Microsoft.AspNetCore.Blazor.Hosting.IWebAssemblyHost host) <0x2160ce8 + 0x00020> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at BitTorrentFileServer.Client.Program.Main (System.String[] args) <0x2010b68 + 0x00014> in <87b360f670124ec0866e539fa2fedc12>:0 
```

**Comment by Tarmil** [comment] 2019-03-20 13:38
I think these two exceptions are instances of the same problem as #22. The root cause is a poor choice of API on my part. There are two extension methods on `IServiceCollection` with the same name: `AddRemoting()` and `AddRemoting<T :> IRemoteService>()`. The first one needs to be called on the client side, and the second one on the server side. But what ends up happening is that the server-side one is called even when not passing an explicit type parameter.

There's a fix for this on master, where these extension methods are now moved to separate namespaces, `Bolero.Remoting.Client` and `Bolero.Remoting.Server` respectively, so the confusion won't happen anymore, provided that you only open one of these two namespaces at a time.

It's not published to nuget.org yet, but it is on the nightly CI. You can try it out:
1. ensure you have `source https://ci.appveyor.com/nuget/bolero` in `paket.dependencies`
2. run `.paket/paket update` (this should update Bolero to v0.3.134)
3. add `open Bolero.Remoting.Client` in `Client/Main.fs` and `Client/Startup.fs`
4. add `open Bolero.Remoting.Server` in `Server/Startup.fs`

That should normally fix this issue. We'll probably do a 0.4 release as soon as authentication is done, so this should be on nuget.org soon.

**Comment by ADIX7** [comment] 2019-03-20 14:08
I had previously errors with AddRemoting, found that issue and corrected my code as:
`ClientRemotingExtensions.AddRemoting(services)`

This solved that error. What I posted here is a new issue. I dont think this one is related to #22 

Now I updated to Bolero 0.3.135 but it still does not work. This exception is from Bolero.Remoting.RemotingExtensions.Remote when I try to get my service. There is only 1 version of `Remote<T>` extension method for `ProgramComponent`, right?
I'm not sure if I do something wrong or it is a bug.

Here is my repo: https://github.com/ADIX7/BitTorrentFileServer

Exception:

```
Error: System.InvalidOperationException: constrained call: Bolero.Remoting.IRemoteService is not assignable from BitTorrentFileServer.Service.WebService
  at Bolero.Remoting.RemotingExtensions.Remote[T] (Bolero.IProgramComponent this) <0x2241000 + 0x00018> in <5c8a3ddf24406c66a7450383df3d8a5c>:0 
  at BitTorrentFileServer.Client.Main+FileServerApp.get_Program () <0x2240e08 + 0x0000a> in <cfe399a25af94f2e941d9166f6cff886>:0 
  at Bolero.ProgramComponent`2[model,msg].OnInit () <0x2240770 + 0x00016> in <5c8a3ddf24406c66a7450383df3d8a5c>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x222c4b0 + 0x00038> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.SetDirectParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x223d4f8 + 0x00084> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderRootComponent (System.Int32 componentId) <0x223c928 + 0x00024> in <7ccdd79bd655431387991356cc8bce62>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x21ad720 + 0x00084> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRenderer () <0x2191970 + 0x00078> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsync (System.Threading.CancellationToken cancellationToken) <0x21630c8 + 0x000f8> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostExtensions.Run (Microsoft.AspNetCore.Blazor.Hosting.IWebAssemblyHost host) <0x2162850 + 0x00020> in <6e8b4c57aeeb4593b71c0de6d0ce9454>:0 
  at BitTorrentFileServer.Client.Program.Main (System.String[] args) <0x20113e0 + 0x00014> in <cfe399a25af94f2e941d9166f6cff886>:0 
```

**Comment by Tarmil** [comment] 2019-03-20 15:21
Ok, this is indeed a different issue. Thanks for the repo, it will help a lot to investigate.

**Comment by ADIX7** [comment] 2019-03-20 15:38
Your welcome! :) I hope you can fix it soon. It's my first F# project, actually I just do it for learning. It seems that it will be good for testing Bolero :D

**Comment by Tarmil** [comment] 2019-03-20 16:49
Ah, I just found the issue. Or rather, I found how to fix it, even though I don't quite understand why it causes this particular error 😄

In the project file `Shared.fsproj`, you need to replate this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

with this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

because it's a library project: the `.Web` SDK is only for web application projects. I don't know why this causes this exception in particular, but I can run the project with this change.

**Comment by ADIX7** [comment] 2019-03-20 17:39
Intresting... Thank you, this solved the problem.

**Closed** 2019-03-20 18:12 UTC
