### ISSUE TITLE
After Upgrading to to 0.23:  WebAssembly error - Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')

### ISSUE THREAD

**Issue by kgday** [fsbolero/Bolero#329] opened 2023-11-03 07:10 UTC
After upgrading to 0.23 the application no longer renders and I get in the developer console of the browser the following error
 Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')

I get a very similar error when I updated my bolero project template and then created a new bolero hosted app from the template.  I post the full console log below:

```
TestBolero.Client.styles.css:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1 blazor Loaded 12.63 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')
      TypeError: Cannot read properties of null (reading 'insertBefore')
          at x (http://localhost:5000/_framework/blazor.webassembly.js:1:17125)
          at se.insertElement (http://localhost:5000/_framework/blazor.webassembly.js:1:23808)
          at se.insertFrame (http://localhost:5000/_framework/blazor.webassembly.js:1:22854)
          at se.applyEdits (http://localhost:5000/_framework/blazor.webassembly.js:1:21490)
          at se.updateComponent (http://localhost:5000/_framework/blazor.webassembly.js:1:20774)
          at http://localhost:5000/_framework/blazor.webassembly.js:1:59513
          at Vt.Ke._internal.renderBatch (http://localhost:5000/_framework/blazor.webassembly.js:1:59885)
          at Object.Gt [as invokeJSFromDotNet] (http://localhost:5000/_framework/blazor.webassembly.js:1:62728)
          at Object.Ii (http://localhost:5000/_framework/dotnet.7.0.11.sf8asx8yhf.js:5:71974)
          at _mono_wasm_invoke_js_blazor (http://localhost:5000/_framework/dotnet.7.0.11.sf8asx8yhf.js:14:103886)
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
    at x (http://localhost:5000/_framework/blazor.webassembly.js:1:17125)
    at se.insertElement (http://localhost:5000/_framework/blazor.webassembly.js:1:23808)
    at se.insertFrame (http://localhost:5000/_framework/blazor.webassembly.js:1:22854)
    at se.applyEdits (http://localhost:5000/_framework/blazor.webassembly.js:1:21490)
    at se.updateComponent (http://localhost:5000/_framework/blazor.webassembly.js:1:20774)
    at http://localhost:5000/_framework/blazor.webassembly.js:1:59513
    at Vt.Ke._internal.renderBatch (http://localhost:5000/_framework/blazor.webassembly.js:1:59885)
    at Object.Gt [as invokeJSFromDotNet] (http://localhost:5000/_framework/blazor.webassembly.js:1:62728)
    at Object.Ii (http://localhost:5000/_framework/dotnet.7.0.11.sf8asx8yhf.js:5:71974)
    at _mono_wasm_invoke_js_blazor (http://localhost:5000/_framework/dotnet.7.0.11.sf8asx8yhf.js:14:103886)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
u @ blazor.webassembly.js:1
_bound_js_globalThis_console_info:7 info: System.Net.Http.HttpClient.Bolero.Remoting.Client.ClientRemoteProvider.LogicalHandler[100]
      Start processing HTTP request POST http://localhost:5000/books/getUsername
_bound_js_globalThis_console_info:7 info: System.Net.Http.HttpClient.Bolero.Remoting.Client.ClientRemoteProvider.ClientHandler[100]
      Sending HTTP request POST http://localhost:5000/books/getUsername
:5000/books/getUsername:1 
        
        
        Failed to load resource: the server responded with a status of 401 (Unauthorized)
_bound_js_globalThis_console_info:7 info: System.Net.Http.HttpClient.Bolero.Remoting.Client.ClientRemoteProvider.ClientHandler[101]
      Received HTTP response headers after 32.5ms - 401
_bound_js_globalThis_console_info:7 info: System.Net.Http.HttpClient.Bolero.Remoting.Client.ClientRemoteProvider.LogicalHandler[101]
      End processing HTTP request after 43.3ms - 401
TestBolero.Client.styles.css:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)

```
In my application that functioned well before the upgrade, the following log I paste below:

```
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1 blazor Loaded 18.89 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')
      TypeError: Cannot read properties of null (reading 'insertBefore')
          at x (http://localhost:51490/_framework/blazor.webassembly.js:1:17125)
          at se.insertElement (http://localhost:51490/_framework/blazor.webassembly.js:1:23808)
          at se.insertFrame (http://localhost:51490/_framework/blazor.webassembly.js:1:22854)
          at se.applyEdits (http://localhost:51490/_framework/blazor.webassembly.js:1:21490)
          at se.updateComponent (http://localhost:51490/_framework/blazor.webassembly.js:1:20774)
          at http://localhost:51490/_framework/blazor.webassembly.js:1:59545
          at Vt.Ke._internal.renderBatch (http://localhost:51490/_framework/blazor.webassembly.js:1:59917)
          at Object.Gt [as invokeJSFromDotNet] (http://localhost:51490/_framework/blazor.webassembly.js:1:62760)
          at Object.Ii (http://localhost:51490/_framework/dotnet.7.0.11.sf8asx8yhf.js:5:71974)
          at _mono_wasm_invoke_js_blazor (http://localhost:51490/_framework/dotnet.7.0.11.sf8asx8yhf.js:14:103886)
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
    at x (http://localhost:51490/_framework/blazor.webassembly.js:1:17125)
    at se.insertElement (http://localhost:51490/_framework/blazor.webassembly.js:1:23808)
    at se.insertFrame (http://localhost:51490/_framework/blazor.webassembly.js:1:22854)
    at se.applyEdits (http://localhost:51490/_framework/blazor.webassembly.js:1:21490)
    at se.updateComponent (http://localhost:51490/_framework/blazor.webassembly.js:1:20774)
    at http://localhost:51490/_framework/blazor.webassembly.js:1:59545
    at Vt.Ke._internal.renderBatch (http://localhost:51490/_framework/blazor.webassembly.js:1:59917)
    at Object.Gt [as invokeJSFromDotNet] (http://localhost:51490/_framework/blazor.webassembly.js:1:62760)
    at Object.Ii (http://localhost:51490/_framework/dotnet.7.0.11.sf8asx8yhf.js:5:71974)
    at _mono_wasm_invoke_js_blazor (http://localhost:51490/_framework/dotnet.7.0.11.sf8asx8yhf.js:14:103886)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
u @ blazor.webassembly.js:1
Ke._internal.dotNetCriticalError @ blazor.webassembly.js:1
_bound_js_Blazor__internal_dotNetCriticalError @ _bound_js_Blazor__internal_dotNetCriticalError:7
Ss @ dotnet.7.0.11.sf8asx8yhf.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.11.sf8asx8yhf.js:14

```

**Comment by Tarmil** [comment] 2023-11-03 08:14
Thanks for the report! Just to make sure: are you using v0.23.43? The earlier v0.23.41 is known to be faulty.

**Comment by Martin521** [comment] 2023-11-03 08:50
To verify the error report, I did
> dotnet new update
> dotnet new bolero-app -o Bolero
> dotnet build

and got
```
MSBuild version 17.5.1+f6fdcf537 for .NET
  Determining projects to restore...
D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj : error NU1108: Cycle detected.  [D:\fsharp\projects\div\Bolero\Bolero.sln]
D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj : error NU1108:   Bolero.Server -> Bolero.Server (>= 0.0.0). [D:\fsharp\projects\div\B
olero\Bolero.sln]
  Failed to restore D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj (in 1.23 sec).
  Restored D:\fsharp\projects\div\Bolero\src\Bolero.Client\Bolero.Client.fsproj (in 1.23 sec).
```

I am not sure if that is in any way related to the above. I should also mention I have .net 8 installed.

**Comment by Martin521** [comment] 2023-11-03 09:05
It also seems that `-s=false` is no longer respected.

Running `dotnet new bolero-app --server=false -o Bolero -v diag` actually shows a line `[2023-11-03 09:58:49.670] [Debug] [Template Engine] => [Execute] => [Template content generation]: [JoinMacro]: Variable 'server{-VALUE-FORMS-}identity' was assigned to value 'False'.` but then creates the server files.

**Comment by Tarmil** [comment] 2023-11-03 09:42
Ah, I think I know why this second issue happens -- I probably forgot to apply the fix for fsbolero/Template#41 in the template definition file. I'll fix it quickly.

**Comment by Tarmil** [comment] 2023-11-03 10:18
> To verify the error report, I did
> 
> > dotnet new update
> > dotnet new bolero-app -o Bolero
> > dotnet build
> 
> and got
> 
> ```
> MSBuild version 17.5.1+f6fdcf537 for .NET
>   Determining projects to restore...
> D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj : error NU1108: Cycle detected.  [D:\fsharp\projects\div\Bolero\Bolero.sln]
> D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj : error NU1108:   Bolero.Server -> Bolero.Server (>= 0.0.0). [D:\fsharp\projects\div\B
> olero\Bolero.sln]
>   Failed to restore D:\fsharp\projects\div\Bolero\src\Bolero.Server\Bolero.Server.fsproj (in 1.23 sec).
>   Restored D:\fsharp\projects\div\Bolero\src\Bolero.Client\Bolero.Client.fsproj (in 1.23 sec).
> ```
> 
> I am not sure if that is in any way related to the above. I should also mention I have .net 8 installed.

Ah, and actually I think the problem here is that since you named your project "Bolero", the server-side project is named "Bolero.Server", which is the same as the NuGet package. So there is an ambiguity. If you name your project something else, this specific issue should not happen.

**Comment by Tarmil** [comment] 2023-11-03 10:25
Regarding your initial issue, can you clean your project (delete obj and bin directories) and try again? I think I've seen this error with projects that were mixing different versions of dependencies due to old files remaining.

**Comment by Tarmil** [comment] 2023-11-03 11:12
Oh I see that you actually get this from a new project. Which .NET SDK version are you using?

**Comment by Martin521** [comment] 2023-11-03 13:38
I just recreated the project and tested it with RC2, same result.

**Comment by fwaris** [comment] 2023-11-03 14:06
Just started seeing this issue also. Happens on a basic template-generated client/server project (created a month or so ago).

Deleted the bin and obj dirs and it still happens

Using: Windows / .net7 / Edge

Setting the versions to 0.22.* for Bolero fixes this issue

Note: Client only project seems to be ok

**Comment by Tarmil** [comment] 2023-11-03 14:52
Thanks everyone, I can reproduce the issue. It seems specific to hosted webassembly projects; client-only works, as mentioned, and server mode (`AddBoleroHost(server = true)`) works too.

**Comment by Tarmil** [comment] 2023-11-03 16:46
I just published Bolero 0.23.44 which should fix this issue. Can you confirm?

**Comment by Martin521** [comment] 2023-11-03 20:16
Yes, works fine now. Thanks!

**Comment by kgday** [comment] 2023-11-03 22:45
Confirmed it works.  Thank you very much for you hard efforts.

**Comment by fwaris** [comment] 2023-11-05 17:47
+1 - thanks

**Closed** 2023-11-06 19:55 UTC
Labels: bug
